[admin]
user = "root"
password = "root"
path = "_"

[proxy]
host = "127.0.0.1"
ports = [8080]
log_dir = "_logs"
enable_tls = false

[proxy.routes]
data = "data.sqlite" # path to sqlite database or json file
storage_driver = "db" # db or file
refresh_interval = 60 # seconds
not_found = {
  type = "json",
  content = "{\"error\":\"no servers configured\"}"}
}

[proxy.discovery]
path = "_discovery" # path to provide discovery data on
allow_external = false # allow external discovery requests
refresh_interval = 60 # seconds
