/*
 * This file was generated by gots, do not edit it manually
 * You can find the docs and source code at https://github.com/aosasona/gots
 */
	
export type Proxy = {
    host?: string;
    http_port?: number;
    https_port?: number;
    enable_tls?: boolean;
    tls_email?: string;
    enable_https_redirect?: boolean;
    config_path?: string;
    storage?: 'json' | 'sqlite' | 'memory';
    cnames?: string[];
};

export type Admin = {
    enabled?: boolean;
    port?: number;
    api_key?: string;
};

export type DomainStatusDNS = {
    value: 'verified' | 'pending' | 'aborted' | 'failed';
    current_retry_count: number;
    last_updated: number;
};

export type DomainStatus = {
    dns: DomainStatusDNS;
};

export type Domain = {
    name: string;
    status?: DomainStatus;
};

export type Service = {
    host?: string;
    port?: number;
    path?: string;
    enable_tls?: boolean;
    domains?: Domain[];
    strip_headers?: string[];
};

export type Config = {
    admin?: Admin;
    services?: Record<string, Service>;
    proxy?: Proxy;
};